server.port=8888
eureka.client.service-url.defaultZone=http://odoru-annuaire:8761/eureka/
management.zipkin.tracing.endpoint=http://odoru-zipkin:9411/api/v2/spans

# ROUTE 1 : MEMBRES
spring.cloud.gateway.routes[0].id=route-membre-service
spring.cloud.gateway.routes[0].uri=lb://ODORU-MEMBRESERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/membres/**

# ROUTE 2 : BADGES
spring.cloud.gateway.routes[1].id=route-badge-service
spring.cloud.gateway.routes[1].uri=lb://Oduro-BadgesService
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/badges/**

# ROUTE 3 : STATS
spring.cloud.gateway.routes[2].id=route-stats-service
spring.cloud.gateway.routes[2].uri=lb://Odoru-Stats
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/stats/**

# ROUTE 4 : COURS
spring.cloud.gateway.routes[3].id=route-cours-service
spring.cloud.gateway.routes[3].uri=lb://Odoru-CoursService
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/cours/**
