server.port=8085
spring.datasource.url=jdbc:mysql://odoru-db-badges:3306/odoru_badges?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=my-secret-pw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

eureka.client.serviceUrl.defaultZone=http://odoru-annuaire:8761/eureka/
eureka.instance.prefer-ip-address=true
zipkin.tracing.endpoint=http://odoru-zipkin:9411/api/v2/spans

spring.rabbitmq.host=odoru-rabbitmq
